"""
Django settings for finance_tracker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x07)9hhnw))37)#gzw=&u#vwe%clu=*xuc&+cxr95(&ouw=n@d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Add this anywhere in settings.py to override the default user:
# Format is 'app_name.ModelName'
AUTH_USER_MODEL = 'tracker.TrackerUser'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',   # first created app in this project, so important to register here.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finance_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finance_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# The URL path prefix that browser will use to request the static files.
# Whenever an html file creates a url for a static file, it gets prefixed with this.
STATIC_URL = 'static/'

# Your Drafting Desk: Where Django looks for custom static files 
# during local development
STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static'),
]

# The Locked Briefcase: Where Django will collect everything when we go live
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')





# The URL path prefix that browser will use to request the image
# Whenever an html file creates a url for an image, it gets prefixed with this.
MEDIA_URL = '/media/'

# The physical folder on the machine where Django will save the uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Since we are using CBVs for authentication, we can't change the redirect
# in the view. Instead, we write it here in settings.py, as follows.
LOGIN_REDIRECT_URL = 'dashboard' # goes to the dashboard url after successful login.
LOGOUT_REDIRECT_URL = 'login' # goes to the login page after logging out.
LOGIN_URL = 'login' # Tells the @login_required decorator where to send unauthorized users.