"""
Django settings for finance_tracker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv   # this is imported to get load_dotenv method in our settings.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# This method wakes up the dotenv robot which then, Loads the environment variables
# from the .env file and pastes them in the OS's Environment of this project. 
# Environment is a temporary memory given to each process by the OS where we can store
# data in the form of environment variables.
load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
# os is the python's built in library that helps it to talk to the underlying OS.
# environ is the dictionary representing the Environment's sticky notes, i.e., the variables and their values.
# .get(), we know already, safely returns the value of the key asked in ().
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# The OS always speaks in strings, no numbers and boolean values. So, it returns, say True
# but in string form. So, it returns "True". But DJ needs a strict bool here. So, the 
# problem is that even if OS return "False", since it's a NON-EMPTY STRING, it is
# evaluated by DJ as True, and hence, DEBUG will always be True, leading to a massive threat.
# that's why we check through a conditional statement, that is bound to return a bool value.
# If returned value is "True", we will get True, else no matter what, even if empty, we 
# will get False
DEBUG = os.environ.get('DEBUG') == 'True'

ALLOWED_HOSTS = []

# Add this anywhere in settings.py to override the default user:
# Format is 'app_name.ModelName'
AUTH_USER_MODEL = 'tracker.TrackerUser'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',   # first created app in this project, so important to register here.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finance_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finance_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# The URL path prefix that browser will use to request the static files.
# Whenever an html file creates a url for a static file, it gets prefixed with this.
STATIC_URL = 'static/'

# Your Drafting Desk: Where Django looks for custom static files 
# during local development
STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static'),
]

# The Locked Briefcase: Where Django will collect everything when we go live
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')





# The URL path prefix that browser will use to request the image
# Whenever an html file creates a url for an image, it gets prefixed with this.
MEDIA_URL = '/media/'

# The physical folder on the machine where Django will save the uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Since we are using CBVs for authentication, we can't change the redirect
# in the view. Instead, we write it here in settings.py, as follows.
LOGIN_REDIRECT_URL = 'dashboard' # goes to the dashboard url after successful login.
LOGOUT_REDIRECT_URL = 'login' # goes to the login page after logging out.
LOGIN_URL = 'login' # Tells the @login_required decorator where to send unauthorized users.